import { renderWithHandlebars } from "../../src/report/generate";

export type RenderInput = Parameters<typeof renderWithHandlebars>[0];

export function makeRenderInput(overrides: Partial<RenderInput> = {}): RenderInput {
  const empty = { dates: [], series: {} };
  return {
    projectKey: "TEST",
    jiraBaseUrl: "https://test.atlassian.net",
    generatedAt: "2025-01-01 00:00:00",
    lastSnapshotDate: "2025-01-01",
    lastSyncAt: null,
    isSyncStale: false,
    kpis: {
      leadTimeMedian: null,
      cycleTimeMedian: null,
      throughputCount: null,
      wipCount: null,
      bugThroughputCount: null,
      bugCycleTimeMedian: null,
      flowEfficiencyAggregate: null,
      devTimeAvgBugRatio: null,
      stageTimeDevMedian: null,
      stageTimeQaMedian: null,
      stageTimePoMedian: null,
      wipDev: null,
      wipQa: null,
      wipPo: null,
      reworkRatio: null,
      avgReworks: null,
      ftrDev: null,
      ftrQa: null,
      ftrPo: null,
    },
    charts: {
      leadTime: empty,
      cycleTime: empty,
      throughput: empty,
      throughputWeighted: empty,
      wip: empty,
      bugThroughput: empty,
      bugCycleTime: empty,
      leadTimeNormalized: empty,
      cycleTimeNormalized: empty,
      flowEfficiency: empty,
      agingWipRisk: empty,
      devTimeAllocation: empty,
      bugBacklog: empty,
      stageTimeByRole: empty,
      stageTimeByRoleP85: empty,
      stageTimeShare: empty,
      wipPerRole: empty,
      stageThroughputNet: empty,
      handoffReworkRatio: empty,
      handoffReworkByType: empty,
      ftrByRole: empty,
      bottleneckScores: empty,
    },
    leadBySize: {},
    cycleBySize: {},
    leadTimeBySizeCharts: {},
    cycleTimeBySizeCharts: {},
    agingWip: {
      asOf: "2025-01-01",
      count: 0,
      percentiles: { p50: 0, p85: 0, p95: 0 },
      riskCounts: { ok: 0, watch: 0, atRisk: 0, critical: 0 },
      issues: [],
      unit: "j",
    },
    forecast: {
      recentWeeks: [],
      weeksUsed: 0,
      byHorizon: [],
      simulations: 0,
      unit: "issues",
    },
    histogram: [],
    cycleStats: { median: 0, p85: 0, p95: 0, avg: 0, count: 0 },
    bottleneck: {
      count: 0, primaryBottleneck: null, primaryColumn: null, recommendation: "",
      byRole: {
        dev: { score: 0, rank: 3, dominantSignal: "combined" as const, dominantColumn: null, signals: { stageTimeMedianDays: 0, avgNetFlow: 0, reworkInboundRate: 0, ftrPenalty: 0 } },
        qa:  { score: 0, rank: 3, dominantSignal: "combined" as const, dominantColumn: null, signals: { stageTimeMedianDays: 0, avgNetFlow: 0, reworkInboundRate: 0, ftrPenalty: 0 } },
        po:  { score: 0, rank: 3, dominantSignal: "combined" as const, dominantColumn: null, signals: { stageTimeMedianDays: 0, avgNetFlow: 0, reworkInboundRate: 0, ftrPenalty: 0 } },
      },
      byColumn: [],
    },
    distribution: {
      cycle: { global: { count: 0, max: 0, hasKde: false, bins: [], kde: [] }, byBucket: {} },
      lead:  { global: { count: 0, max: 0, hasKde: false, bins: [], kde: [] }, byBucket: {} },
    },
    sprintCharts: null,
    rolesSprintCharts: null,
    ...overrides,
  };
}
